# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-22 15:27
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0002_auto_20180922_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudinaryPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
