# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-22 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0003_cloudinaryphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudinaryphoto',
            name='caption',
        ),
        migrations.AddField(
            model_name='cloudinaryphoto',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloudinaryphoto',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
