# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-22 16:48
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0004_auto_20181022_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudinaryphoto',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='stage'),
        ),
    ]
