# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-22 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0005_auto_20181022_1148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CloudinaryPhoto',
        ),
    ]
