# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-23 23:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180823_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 23, 23, 13, 28, 697558, tzinfo=utc)),
        ),
    ]
