# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-04 02:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180922_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 4, 2, 57, 38, 534258, tzinfo=utc)),
        ),
    ]
