# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-28 20:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20180928_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 28, 20, 54, 35, 730690, tzinfo=utc)),
        ),
    ]
