# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-16 03:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20181016_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 16, 3, 14, 44, 814075, tzinfo=utc)),
        ),
    ]
