# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-20 21:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20181016_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 20, 21, 57, 14, 648827, tzinfo=utc)),
        ),
    ]
