# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-21 00:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20181020_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 21, 0, 26, 24, 866092, tzinfo=utc)),
        ),
    ]
