# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-22 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20180928_1554'),
        ('blog', '0022_auto_20181021_0026'),
    ]

    operations = [
    ]
